name: Update DB weekly

on: #push
  workflow_dispatch:
  schedule:
    - cron: "2 5 * * THU"

# env:
#     NAME: value

jobs:
  modify-db:
    name: Update json file via Python
    runs-on: ubuntu-latest
    # Expose step outputs as job outputs
    outputs:
      changes: ${{ steps.scrapestep.outputs.changes }}
    steps:
      - name: Check-out repo for use
        uses: actions/checkout@v4
        with:
          # repository: universallyleo/ngzkHandshakeScrape
          ref: main
        # token: ${{ secrets.GITHUB_TOKEN }}
        # path: ${{ env.DEVOPS_DIR }}

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # install the python version needed

      - name: Install python packages
        run: pip install -r requirements.txt

      - name: Get current date
        id: date
        run: echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Copy original json
        run: cp ./src/lib/data/current.json ./src/lib/data/old/backup_at_${{ env.today }}.json

      - name: Scrape with Python # run scrape.py, set output var "changes"
        id: scrapestep
        env:
          COOKIES: ${{ secrets.FORTUNE_COOKIES }}
          FIREBASE_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: python scrape.py old/backup_at_${{ env.today }}.json

      - name: Auto commit
        if: steps.scrapestep.outputs.changes == 'new'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: Auto DB update ${{ env.today }}

  confirm-job-output:
    runs-on: ubuntu-latest
    needs: modify-db
    steps:
      - env:
          CHANGES: ${{needs.modify-db.outputs.changes}}
        run: echo "$CHANGES"
        
  commit-if-change:  # to run action in own repo, need to use it as a job, not a step
    needs: modify-db
    if: needs.modify-db.outputs.changes == 'new'
    uses: ./.github/workflows/build.yml
