name: Update DB weekly

on: #push
  workflow_dispatch:
  schedule:
    - cron: "2 5 * * THU"

# env:
#     NAME: value

jobs:
  modify-db:
    name: Update json file via Python
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repo for use
        uses: actions/checkout@v4
        with:
          # repository: universallyleo/ngzkHandshakeScrape
          ref: main
        # token: ${{ secrets.GITHUB_TOKEN }}
        # path: ${{ env.DEVOPS_DIR }}

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # install the python version needed

      - name: Install python packages
        run: pip install -r requirements.txt

      - name: Get current date
        id: date
        run: echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Copy original json
        run: cp ./src/lib/data/current.json ./src/lib/data/old/backup_at_${{ env.today }}.json

      - name: Scrape with Python # run scrape.py
        env:
          COOKIES: ${{ secrets.FORTUNE_COOKIES }}
          FIREBASE_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: python scrape.py old/backup_at_${{ env.today }}.json

  commit-if-change:
    name: Check change and commit
    needs: modify-db
    runs-on: ubuntu-latest
    if: needs.modify-db.output.changes == 'new'
    steps:
      # - name: Setup and Build with Nodejs
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20.x'
      #     cache: "npm"
      # - run: npm ci ## clean install
      # - run: npm run build
      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: Auto DB update ${{ env.today }}
      - name: GH Page deploy
        uses: ./.github/workflows/build.yml
